git clone -b 8.0 https://github.com/avanzosc/odoo-addons.git /home/odoo/v8/github/avanzosc/odoo-addons
git clone -b 8.0 https://github.com/odoomrp/odoomrp-wip.git /home/odoo/v8/github/odoomrp-wip
git clone -b 8.0 https://github.com/odoomrp/odoomrp-utils.git /home/odoo/v8/github/odoomrp-utils
git clone -b 8.0 https://github.com/OCA/account-analytic.git /home/odoo/v8/github/OCA/account-analytic
git clone -b 8.0 https://github.com/OCA/account-financial-reporting.git /home/odoo/v8/github/OCA/account-financial-reporting
git clone -b 8.0 https://github.com/OCA/account-financial-tools.git /home/odoo/v8/github/OCA/account-financial-tools
git clone -b 8.0 https://github.com/OCA/account-invoicing.git /home/odoo/v8/github/OCA/account-invoicing
git clone -b 8.0 https://github.com/OCA/account-payment.git /home/odoo/v8/github/OCA/account-payment
git clone -b 8.0 https://github.com/OCA/bank-payment.git /home/odoo/v8/github/OCA/bank-payment
git clone -b 8.0 https://github.com/OCA/bank-statement-import.git /home/odoo/v8/github/OCA/bank-statement-import
git clone -b 8.0 https://github.com/OCA/bank-statement-reconcile.git /home/odoo/v8/github/OCA/bank-statement-reconcile
git clone -b 8.0 https://github.com/OCA/l10n-spain.git /home/odoo/v8/github/OCA/l10n-spain
#!/bin/bash
git clone -b 8.0 https://github.com/OCA/manufacture.git /home/odoo/v8/github/OCA/manufacture
git clone -b 8.0 https://github.com/OCA/partner-contact.git /home/odoo/v8/github/OCA/partner-contact
git clone -b 8.0 https://github.com/OCA/product-attribute.git /home/odoo/v8/github/OCA/product-attribute
git clone -b 8.0 https://github.com/OCA/product-variant.git /home/odoo/v8/github/OCA/product-variant
git clone -b 8.0 https://github.com/OCA/project.git /home/odoo/v8/github/OCA/project
git clone -b 8.0 https://github.com/OCA/purchase-workflow.git /home/odoo/v8/github/OCA/purchase-workflow
git clone -b 8.0 https://github.com/OCA/report-print-send.git /home/odoo/v8/github/OCA/report-print-send
git clone -b 8.0 https://github.com/OCA/reporting-engine.git /home/odoo/v8/github/OCA/reporting-engine
git clone -b 8.0 https://github.com/OCA/sale-workflow.git /home/odoo/v8/github/OCA/sale-workflow
git clone -b 8.0 https://github.com/OCA/server-tools.git /home/odoo/v8/github/OCA/server-tools
git clone -b 8.0 https://github.com/OCA/stock-logistics-warehouse.git /home/odoo/v8/github/OCA/stock-logistics-warehouse
git clone -b 8.0 https://github.com/OCA/stock-logistics-workflow.git /home/odoo/v8/github/OCA/stock-logistics-workflow
git clone -b 8.0 https://github.com/OCA/web.git /home/odoo/v8/github/OCA/web
git clone -b 8.0 https://github.com/OCA/website.git /home/odoo/v8/github/OCA/website
git clone -b 8.0 https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons.git /opt/odoo/v8/github/serviciosbaeza
